name: Notify Blog on Project Update

on:
  push:
    branches:
      - blog

jobs:
  notify-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch to blog
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.BLOG_PAT }}
          repository: lucascarpantonio/lucascarpantonio.github.io
          event-type: update_project
          client-payload: |
            {
              "title": "NEO Project",
              "repo_url": "https://github.com/lucascarpantonio/NEO_Project",
              "description": "A Python-based pipeline for extracting and analyzing NASA Near-Earth Object data.",
              "tags": "data science, python, nasa api"
            }